// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {modules} from '../models';

export function Add(arg1:modules.Bookmark):Promise<modules.Bookmark>;

export function Delete(arg1:string):Promise<void>;

export function ImportEdgeHTML(arg1:string):Promise<number>;

export function List(arg1:string):Promise<Array<modules.Bookmark>>;
