// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActionQueue():Promise<Record<string, any>>;

export function Call(arg1:string,arg2:string,arg3:Record<string, any>):Promise<Record<string, any>>;

export function Configure(arg1:string,arg2:string,arg3:number):Promise<void>;

export function ExecuteAction(arg1:string):Promise<Record<string, any>>;

export function Logs():Promise<Array<string>>;

export function ReadConfig():Promise<string>;

export function Restart():Promise<void>;

export function SendNLP(arg1:string):Promise<Record<string, any>>;

export function SetConfigPath(arg1:string):Promise<void>;

export function Start():Promise<void>;

export function Status():Promise<Record<string, any>>;

export function Stop():Promise<void>;

export function TopK():Promise<Record<string, any>>;

export function WriteConfig(arg1:string):Promise<void>;
