// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Capture(arg1, arg2, arg3) {
  return window['go']['modules']['FleetingService']['Capture'](arg1, arg2, arg3);
}

export function Delete(arg1) {
  return window['go']['modules']['FleetingService']['Delete'](arg1);
}

export function Promote(arg1, arg2, arg3) {
  return window['go']['modules']['FleetingService']['Promote'](arg1, arg2, arg3);
}

export function Stream(arg1) {
  return window['go']['modules']['FleetingService']['Stream'](arg1);
}
