// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Enable(arg1, arg2) {
  return window['go']['modules']['PluginsService']['Enable'](arg1, arg2);
}

export function IsEnabled(arg1) {
  return window['go']['modules']['PluginsService']['IsEnabled'](arg1);
}

export function List() {
  return window['go']['modules']['PluginsService']['List']();
}

export function LoadEntry(arg1, arg2) {
  return window['go']['modules']['PluginsService']['LoadEntry'](arg1, arg2);
}

export function OpenFolder(arg1) {
  return window['go']['modules']['PluginsService']['OpenFolder'](arg1);
}
