// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {modules} from '../models';

export function Add(arg1:modules.Shortcut):Promise<modules.Shortcut>;

export function Delete(arg1:string):Promise<void>;

export function List():Promise<Array<modules.Shortcut>>;

export function Open(arg1:string):Promise<void>;

export function OpenInExplorer(arg1:string):Promise<void>;

export function OpenInTerminal(arg1:string):Promise<void>;

export function OpenInVSCode(arg1:string):Promise<void>;
