// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Add(arg1) {
  return window['go']['modules']['BookmarksService']['Add'](arg1);
}

export function Delete(arg1) {
  return window['go']['modules']['BookmarksService']['Delete'](arg1);
}

export function ImportEdgeHTML(arg1) {
  return window['go']['modules']['BookmarksService']['ImportEdgeHTML'](arg1);
}

export function List(arg1) {
  return window['go']['modules']['BookmarksService']['List'](arg1);
}
