// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Boards(arg1) {
  return window['go']['modules']['CreativeService']['Boards'](arg1);
}

export function DeleteBoard(arg1) {
  return window['go']['modules']['CreativeService']['DeleteBoard'](arg1);
}

export function LogWriting(arg1, arg2) {
  return window['go']['modules']['CreativeService']['LogWriting'](arg1, arg2);
}

export function SaveBoard(arg1) {
  return window['go']['modules']['CreativeService']['SaveBoard'](arg1);
}

export function WritingStats(arg1) {
  return window['go']['modules']['CreativeService']['WritingStats'](arg1);
}
