// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {modules} from '../models';

export function Boards(arg1:string):Promise<Array<modules.Board>>;

export function DeleteBoard(arg1:string):Promise<void>;

export function LogWriting(arg1:number,arg2:string):Promise<modules.WritingSession>;

export function SaveBoard(arg1:modules.Board):Promise<modules.Board>;

export function WritingStats(arg1:number):Promise<Record<string, any>>;
