// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportAll():Promise<string>;

export function Heatmap(arg1:number):Promise<Array<Record<string, any>>>;

export function Overview():Promise<Record<string, any>>;

export function YearReview(arg1:number):Promise<string>;
