// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportAll() {
  return window['go']['modules']['DataService']['ExportAll']();
}

export function Heatmap(arg1) {
  return window['go']['modules']['DataService']['Heatmap'](arg1);
}

export function Overview() {
  return window['go']['modules']['DataService']['Overview']();
}

export function YearReview(arg1) {
  return window['go']['modules']['DataService']['YearReview'](arg1);
}
