// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {modules} from '../models';

export function AddEdge(arg1:string,arg2:string,arg3:string):Promise<modules.DetectiveEdge>;

export function Board():Promise<Record<string, any>>;

export function DeleteEdge(arg1:string):Promise<void>;

export function DeleteNode(arg1:string):Promise<void>;

export function Export():Promise<string>;

export function Move(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SaveNode(arg1:modules.DetectiveNode):Promise<modules.DetectiveNode>;
