// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddEdge(arg1, arg2, arg3) {
  return window['go']['modules']['DetectiveService']['AddEdge'](arg1, arg2, arg3);
}

export function Board() {
  return window['go']['modules']['DetectiveService']['Board']();
}

export function DeleteEdge(arg1) {
  return window['go']['modules']['DetectiveService']['DeleteEdge'](arg1);
}

export function DeleteNode(arg1) {
  return window['go']['modules']['DetectiveService']['DeleteNode'](arg1);
}

export function Export() {
  return window['go']['modules']['DetectiveService']['Export']();
}

export function Move(arg1, arg2, arg3) {
  return window['go']['modules']['DetectiveService']['Move'](arg1, arg2, arg3);
}

export function SaveNode(arg1) {
  return window['go']['modules']['DetectiveService']['SaveNode'](arg1);
}
