// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {modules} from '../models';

export function Delete(arg1:string):Promise<void>;

export function List(arg1:number):Promise<Array<modules.DiaryEntry>>;

export function OnThisDay():Promise<Array<modules.DiaryEntry>>;

export function Save(arg1:modules.DiaryEntry):Promise<modules.DiaryEntry>;

export function Summary(arg1:string):Promise<Record<string, any>>;
