// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Delete(arg1) {
  return window['go']['modules']['DiaryService']['Delete'](arg1);
}

export function List(arg1) {
  return window['go']['modules']['DiaryService']['List'](arg1);
}

export function OnThisDay() {
  return window['go']['modules']['DiaryService']['OnThisDay']();
}

export function Save(arg1) {
  return window['go']['modules']['DiaryService']['Save'](arg1);
}

export function Summary(arg1) {
  return window['go']['modules']['DiaryService']['Summary'](arg1);
}
