// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActionQueue() {
  return window['go']['modules']['FascinatorService']['ActionQueue']();
}

export function Call(arg1, arg2, arg3) {
  return window['go']['modules']['FascinatorService']['Call'](arg1, arg2, arg3);
}

export function Configure(arg1, arg2, arg3) {
  return window['go']['modules']['FascinatorService']['Configure'](arg1, arg2, arg3);
}

export function ExecuteAction(arg1) {
  return window['go']['modules']['FascinatorService']['ExecuteAction'](arg1);
}

export function Logs() {
  return window['go']['modules']['FascinatorService']['Logs']();
}

export function ReadConfig() {
  return window['go']['modules']['FascinatorService']['ReadConfig']();
}

export function Restart() {
  return window['go']['modules']['FascinatorService']['Restart']();
}

export function SendNLP(arg1) {
  return window['go']['modules']['FascinatorService']['SendNLP'](arg1);
}

export function SetConfigPath(arg1) {
  return window['go']['modules']['FascinatorService']['SetConfigPath'](arg1);
}

export function Start() {
  return window['go']['modules']['FascinatorService']['Start']();
}

export function Status() {
  return window['go']['modules']['FascinatorService']['Status']();
}

export function Stop() {
  return window['go']['modules']['FascinatorService']['Stop']();
}

export function TopK() {
  return window['go']['modules']['FascinatorService']['TopK']();
}

export function WriteConfig(arg1) {
  return window['go']['modules']['FascinatorService']['WriteConfig'](arg1);
}
