// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteSubscription(arg1) {
  return window['go']['modules']['FinanceService']['DeleteSubscription'](arg1);
}

export function DeleteTransaction(arg1) {
  return window['go']['modules']['FinanceService']['DeleteTransaction'](arg1);
}

export function ImportCSV(arg1, arg2) {
  return window['go']['modules']['FinanceService']['ImportCSV'](arg1, arg2);
}

export function SaveSubscription(arg1) {
  return window['go']['modules']['FinanceService']['SaveSubscription'](arg1);
}

export function SaveTransaction(arg1) {
  return window['go']['modules']['FinanceService']['SaveTransaction'](arg1);
}

export function Subscriptions() {
  return window['go']['modules']['FinanceService']['Subscriptions']();
}

export function Summary(arg1) {
  return window['go']['modules']['FinanceService']['Summary'](arg1);
}

export function Transactions(arg1, arg2, arg3) {
  return window['go']['modules']['FinanceService']['Transactions'](arg1, arg2, arg3);
}
