// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {modules} from '../models';

export function DeleteSubscription(arg1:string):Promise<void>;

export function DeleteTransaction(arg1:string):Promise<void>;

export function ImportCSV(arg1:string,arg2:string):Promise<number>;

export function SaveSubscription(arg1:modules.Subscription):Promise<modules.Subscription>;

export function SaveTransaction(arg1:modules.Transaction):Promise<modules.Transaction>;

export function Subscriptions():Promise<Array<modules.Subscription>>;

export function Summary(arg1:number):Promise<Record<string, any>>;

export function Transactions(arg1:string,arg2:string,arg3:number):Promise<Array<modules.Transaction>>;
