// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {modules} from '../models';

export function Capture(arg1:string,arg2:Array<string>,arg3:string):Promise<modules.Fleeting>;

export function Delete(arg1:string):Promise<void>;

export function Promote(arg1:string,arg2:string,arg3:string):Promise<string>;

export function Stream(arg1:number):Promise<Array<modules.Fleeting>>;
