// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Delete(arg1) {
  return window['go']['modules']['HealthService']['Delete'](arg1);
}

export function Log(arg1, arg2, arg3, arg4) {
  return window['go']['modules']['HealthService']['Log'](arg1, arg2, arg3, arg4);
}

export function Overview() {
  return window['go']['modules']['HealthService']['Overview']();
}

export function Series(arg1, arg2) {
  return window['go']['modules']['HealthService']['Series'](arg1, arg2);
}
