// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {modules} from '../models';

export function Delete(arg1:string):Promise<void>;

export function Log(arg1:string,arg2:number,arg3:string,arg4:string):Promise<modules.HabitLog>;

export function Overview():Promise<Array<Record<string, any>>>;

export function Series(arg1:string,arg2:number):Promise<Array<modules.HabitLog>>;
