// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Actions(arg1) {
  return window['go']['modules']['InstituteService']['Actions'](arg1);
}

export function DeleteAction(arg1) {
  return window['go']['modules']['InstituteService']['DeleteAction'](arg1);
}

export function DeleteDept(arg1) {
  return window['go']['modules']['InstituteService']['DeleteDept'](arg1);
}

export function DeletePhase(arg1) {
  return window['go']['modules']['InstituteService']['DeletePhase'](arg1);
}

export function Depts() {
  return window['go']['modules']['InstituteService']['Depts']();
}

export function Phases(arg1) {
  return window['go']['modules']['InstituteService']['Phases'](arg1);
}

export function SaveAction(arg1) {
  return window['go']['modules']['InstituteService']['SaveAction'](arg1);
}

export function SaveDept(arg1) {
  return window['go']['modules']['InstituteService']['SaveDept'](arg1);
}

export function SavePhase(arg1) {
  return window['go']['modules']['InstituteService']['SavePhase'](arg1);
}
