// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {modules} from '../models';

export function Actions(arg1:string):Promise<Array<modules.InstAction>>;

export function DeleteAction(arg1:string):Promise<void>;

export function DeleteDept(arg1:string):Promise<void>;

export function DeletePhase(arg1:string):Promise<void>;

export function Depts():Promise<Array<modules.Department>>;

export function Phases(arg1:string):Promise<Array<modules.Phase>>;

export function SaveAction(arg1:modules.InstAction):Promise<modules.InstAction>;

export function SaveDept(arg1:modules.Department):Promise<modules.Department>;

export function SavePhase(arg1:modules.Phase):Promise<modules.Phase>;
