// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Cards(arg1, arg2) {
  return window['go']['modules']['LearningService']['Cards'](arg1, arg2);
}

export function Decks() {
  return window['go']['modules']['LearningService']['Decks']();
}

export function DeleteCard(arg1) {
  return window['go']['modules']['LearningService']['DeleteCard'](arg1);
}

export function DeleteDeck(arg1) {
  return window['go']['modules']['LearningService']['DeleteDeck'](arg1);
}

export function Import(arg1, arg2) {
  return window['go']['modules']['LearningService']['Import'](arg1, arg2);
}

export function Quiz(arg1, arg2) {
  return window['go']['modules']['LearningService']['Quiz'](arg1, arg2);
}

export function Review(arg1, arg2) {
  return window['go']['modules']['LearningService']['Review'](arg1, arg2);
}

export function SaveCard(arg1) {
  return window['go']['modules']['LearningService']['SaveCard'](arg1);
}

export function SaveDeck(arg1) {
  return window['go']['modules']['LearningService']['SaveDeck'](arg1);
}
