// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {modules} from '../models';

export function Cards(arg1:string,arg2:boolean):Promise<Array<modules.Card>>;

export function Decks():Promise<Array<Record<string, any>>>;

export function DeleteCard(arg1:string):Promise<void>;

export function DeleteDeck(arg1:string):Promise<void>;

export function Import(arg1:string,arg2:string):Promise<number>;

export function Quiz(arg1:string,arg2:number):Promise<Array<modules.Card>>;

export function Review(arg1:string,arg2:number):Promise<Record<string, any>>;

export function SaveCard(arg1:modules.Card):Promise<modules.Card>;

export function SaveDeck(arg1:string):Promise<modules.Deck>;
