// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {modules} from '../models';

export function AddPodcast(arg1:string,arg2:string):Promise<modules.Podcast>;

export function DeletePodcast(arg1:string):Promise<void>;

export function Play(arg1:string,arg2:string):Promise<void>;

export function Podcasts():Promise<Array<modules.Podcast>>;

export function Refresh(arg1:string):Promise<modules.Podcast>;

export function Scan(arg1:string):Promise<Array<modules.Track>>;
