// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddPodcast(arg1, arg2) {
  return window['go']['modules']['MusicService']['AddPodcast'](arg1, arg2);
}

export function DeletePodcast(arg1) {
  return window['go']['modules']['MusicService']['DeletePodcast'](arg1);
}

export function Play(arg1, arg2) {
  return window['go']['modules']['MusicService']['Play'](arg1, arg2);
}

export function Podcasts() {
  return window['go']['modules']['MusicService']['Podcasts']();
}

export function Refresh(arg1) {
  return window['go']['modules']['MusicService']['Refresh'](arg1);
}

export function Scan(arg1) {
  return window['go']['modules']['MusicService']['Scan'](arg1);
}
