// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Encode(arg1, arg2) {
  return window['go']['modules']['NetService']['Encode'](arg1, arg2);
}

export function HTTPRequest(arg1, arg2, arg3, arg4) {
  return window['go']['modules']['NetService']['HTTPRequest'](arg1, arg2, arg3, arg4);
}

export function LocalInfo() {
  return window['go']['modules']['NetService']['LocalInfo']();
}

export function Lookup(arg1) {
  return window['go']['modules']['NetService']['Lookup'](arg1);
}

export function Ping(arg1) {
  return window['go']['modules']['NetService']['Ping'](arg1);
}

export function RegexTest(arg1, arg2, arg3) {
  return window['go']['modules']['NetService']['RegexTest'](arg1, arg2, arg3);
}
