// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Encode(arg1:string,arg2:string):Promise<string>;

export function HTTPRequest(arg1:string,arg2:string,arg3:Record<string, string>,arg4:string):Promise<Record<string, any>>;

export function LocalInfo():Promise<Record<string, any>>;

export function Lookup(arg1:string):Promise<Array<string>>;

export function Ping(arg1:string):Promise<string>;

export function RegexTest(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;
