// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Backlinks(arg1) {
  return window['go']['modules']['NotesService']['Backlinks'](arg1);
}

export function Create(arg1) {
  return window['go']['modules']['NotesService']['Create'](arg1);
}

export function Delete(arg1) {
  return window['go']['modules']['NotesService']['Delete'](arg1);
}

export function Get(arg1) {
  return window['go']['modules']['NotesService']['Get'](arg1);
}

export function List(arg1, arg2) {
  return window['go']['modules']['NotesService']['List'](arg1, arg2);
}

export function Search(arg1) {
  return window['go']['modules']['NotesService']['Search'](arg1);
}

export function Update(arg1) {
  return window['go']['modules']['NotesService']['Update'](arg1);
}
