// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {modules} from '../models';

export function Backlinks(arg1:string):Promise<Array<modules.Note>>;

export function Create(arg1:modules.Note):Promise<modules.Note>;

export function Delete(arg1:string):Promise<void>;

export function Get(arg1:string):Promise<modules.Note>;

export function List(arg1:string,arg2:number):Promise<Array<modules.Note>>;

export function Search(arg1:string):Promise<Array<modules.Note>>;

export function Update(arg1:modules.Note):Promise<void>;
