// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Delete(arg1) {
  return window['go']['modules']['PasswordService']['Delete'](arg1);
}

export function ImportCSV(arg1) {
  return window['go']['modules']['PasswordService']['ImportCSV'](arg1);
}

export function Init(arg1) {
  return window['go']['modules']['PasswordService']['Init'](arg1);
}

export function List() {
  return window['go']['modules']['PasswordService']['List']();
}

export function Lock() {
  return window['go']['modules']['PasswordService']['Lock']();
}

export function Reveal(arg1) {
  return window['go']['modules']['PasswordService']['Reveal'](arg1);
}

export function Save(arg1) {
  return window['go']['modules']['PasswordService']['Save'](arg1);
}

export function Status() {
  return window['go']['modules']['PasswordService']['Status']();
}

export function Unlock(arg1) {
  return window['go']['modules']['PasswordService']['Unlock'](arg1);
}
