// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {modules} from '../models';

export function Delete(arg1:string):Promise<void>;

export function ImportCSV(arg1:string):Promise<number>;

export function Init(arg1:string):Promise<void>;

export function List():Promise<Array<modules.PasswordEntry>>;

export function Lock():Promise<void>;

export function Reveal(arg1:string):Promise<Record<string, string>>;

export function Save(arg1:modules.PasswordEntry):Promise<modules.PasswordEntry>;

export function Status():Promise<Record<string, any>>;

export function Unlock(arg1:string):Promise<boolean>;
