// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';

export function Enable(arg1:string,arg2:boolean):Promise<void>;

export function IsEnabled(arg1:string):Promise<boolean>;

export function List():Promise<Array<core.PluginManifest>>;

export function LoadEntry(arg1:string,arg2:string):Promise<string>;

export function OpenFolder(arg1:string):Promise<void>;
