// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {modules} from '../models';

export function Achievements():Promise<Array<modules.Achievement>>;

export function Award(arg1:number,arg2:string,arg3:string):Promise<void>;

export function CheckAchievements():Promise<Array<string>>;

export function DeleteAchievement(arg1:string):Promise<void>;

export function Profile():Promise<Record<string, any>>;

export function SaveAchievement(arg1:modules.Achievement):Promise<modules.Achievement>;

export function UnlockAchievement(arg1:string):Promise<void>;
