// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Achievements() {
  return window['go']['modules']['RPGService']['Achievements']();
}

export function Award(arg1, arg2, arg3) {
  return window['go']['modules']['RPGService']['Award'](arg1, arg2, arg3);
}

export function CheckAchievements() {
  return window['go']['modules']['RPGService']['CheckAchievements']();
}

export function DeleteAchievement(arg1) {
  return window['go']['modules']['RPGService']['DeleteAchievement'](arg1);
}

export function Profile() {
  return window['go']['modules']['RPGService']['Profile']();
}

export function SaveAchievement(arg1) {
  return window['go']['modules']['RPGService']['SaveAchievement'](arg1);
}

export function UnlockAchievement(arg1) {
  return window['go']['modules']['RPGService']['UnlockAchievement'](arg1);
}
