// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Add(arg1) {
  return window['go']['modules']['ShortcutsService']['Add'](arg1);
}

export function Delete(arg1) {
  return window['go']['modules']['ShortcutsService']['Delete'](arg1);
}

export function List() {
  return window['go']['modules']['ShortcutsService']['List']();
}

export function Open(arg1) {
  return window['go']['modules']['ShortcutsService']['Open'](arg1);
}

export function OpenInExplorer(arg1) {
  return window['go']['modules']['ShortcutsService']['OpenInExplorer'](arg1);
}

export function OpenInTerminal(arg1) {
  return window['go']['modules']['ShortcutsService']['OpenInTerminal'](arg1);
}

export function OpenInVSCode(arg1) {
  return window['go']['modules']['ShortcutsService']['OpenInVSCode'](arg1);
}
