// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {modules} from '../models';

export function Blocks(arg1:string):Promise<Array<modules.TimeBlock>>;

export function DeleteBlock(arg1:string):Promise<void>;

export function SaveBlock(arg1:modules.TimeBlock):Promise<modules.TimeBlock>;

export function SavePomodoro(arg1:modules.Pomodoro):Promise<modules.Pomodoro>;

export function StartTracking():Promise<void>;

export function Stats(arg1:number):Promise<Array<Record<string, any>>>;

export function StopTracking():Promise<void>;

export function TrackingOn():Promise<boolean>;

export function Usage(arg1:string):Promise<Array<Record<string, any>>>;
