// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Blocks(arg1) {
  return window['go']['modules']['TimeService']['Blocks'](arg1);
}

export function DeleteBlock(arg1) {
  return window['go']['modules']['TimeService']['DeleteBlock'](arg1);
}

export function SaveBlock(arg1) {
  return window['go']['modules']['TimeService']['SaveBlock'](arg1);
}

export function SavePomodoro(arg1) {
  return window['go']['modules']['TimeService']['SavePomodoro'](arg1);
}

export function StartTracking() {
  return window['go']['modules']['TimeService']['StartTracking']();
}

export function Stats(arg1) {
  return window['go']['modules']['TimeService']['Stats'](arg1);
}

export function StopTracking() {
  return window['go']['modules']['TimeService']['StopTracking']();
}

export function TrackingOn() {
  return window['go']['modules']['TimeService']['TrackingOn']();
}

export function Usage(arg1) {
  return window['go']['modules']['TimeService']['Usage'](arg1);
}
