// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {modules} from '../models';

export function Create(arg1:modules.Todo):Promise<modules.Todo>;

export function Delete(arg1:string):Promise<void>;

export function DueSoon(arg1:number):Promise<Array<modules.Todo>>;

export function List(arg1:string):Promise<Array<modules.Todo>>;

export function Lists():Promise<Array<Record<string, any>>>;

export function Toggle(arg1:string):Promise<void>;

export function Update(arg1:modules.Todo):Promise<void>;
