// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1) {
  return window['go']['modules']['TodoService']['Create'](arg1);
}

export function Delete(arg1) {
  return window['go']['modules']['TodoService']['Delete'](arg1);
}

export function DueSoon(arg1) {
  return window['go']['modules']['TodoService']['DueSoon'](arg1);
}

export function List(arg1) {
  return window['go']['modules']['TodoService']['List'](arg1);
}

export function Lists() {
  return window['go']['modules']['TodoService']['Lists']();
}

export function Toggle(arg1) {
  return window['go']['modules']['TodoService']['Toggle'](arg1);
}

export function Update(arg1) {
  return window['go']['modules']['TodoService']['Update'](arg1);
}
