// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {modules} from '../models';

export function DeleteEntry(arg1:string):Promise<void>;

export function DeleteTrip(arg1:string):Promise<void>;

export function Entries(arg1:string):Promise<Array<modules.TravelEntry>>;

export function SaveEntry(arg1:modules.TravelEntry):Promise<modules.TravelEntry>;

export function SaveTrip(arg1:modules.Trip):Promise<modules.Trip>;

export function Trips():Promise<Array<modules.Trip>>;
