// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteEntry(arg1) {
  return window['go']['modules']['TravelService']['DeleteEntry'](arg1);
}

export function DeleteTrip(arg1) {
  return window['go']['modules']['TravelService']['DeleteTrip'](arg1);
}

export function Entries(arg1) {
  return window['go']['modules']['TravelService']['Entries'](arg1);
}

export function SaveEntry(arg1) {
  return window['go']['modules']['TravelService']['SaveEntry'](arg1);
}

export function SaveTrip(arg1) {
  return window['go']['modules']['TravelService']['SaveTrip'](arg1);
}

export function Trips() {
  return window['go']['modules']['TravelService']['Trips']();
}
