// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BridgeInfo():Promise<Record<string, any>>;

export function GetFascinatorSettings():Promise<main.FascinatorSettings>;

export function Greet(arg1:string):Promise<string>;

export function ReadPluginFile(arg1:string,arg2:string):Promise<string>;

export function SaveFascinatorSettings(arg1:main.FascinatorSettings):Promise<void>;

export function Version():Promise<string>;
