// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BridgeInfo() {
  return window['go']['main']['App']['BridgeInfo']();
}

export function GetFascinatorSettings() {
  return window['go']['main']['App']['GetFascinatorSettings']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ReadPluginFile(arg1, arg2) {
  return window['go']['main']['App']['ReadPluginFile'](arg1, arg2);
}

export function SaveFascinatorSettings(arg1) {
  return window['go']['main']['App']['SaveFascinatorSettings'](arg1);
}

export function Version() {
  return window['go']['main']['App']['Version']();
}
